// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvM3i-F0vQKDhjWv8_B80kE2HMe8glhVs',
    appId: '1:325179381241:web:648a794d7e9d7352659928',
    messagingSenderId: '325179381241',
    projectId: 'pothole-finder-e323f',
    authDomain: 'pothole-finder-e323f.firebaseapp.com',
    storageBucket: 'pothole-finder-e323f.firebasestorage.app',
    measurementId: 'G-ZS8KVJB4PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzAiXuGJMcbJ_jqOl0PxwB3KR-JmIm3es',
    appId: '1:325179381241:android:e64fb6b4c6ad4c7b659928',
    messagingSenderId: '325179381241',
    projectId: 'pothole-finder-e323f',
    storageBucket: 'pothole-finder-e323f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8vfAaagibZ8AvlyUS6VN8tx69LNgjkbg',
    appId: '1:325179381241:ios:13525de87d72d26e659928',
    messagingSenderId: '325179381241',
    projectId: 'pothole-finder-e323f',
    storageBucket: 'pothole-finder-e323f.firebasestorage.app',
    iosBundleId: 'com.suyashpandya.potholefinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8vfAaagibZ8AvlyUS6VN8tx69LNgjkbg',
    appId: '1:325179381241:ios:c5673770e41a3c50659928',
    messagingSenderId: '325179381241',
    projectId: 'pothole-finder-e323f',
    storageBucket: 'pothole-finder-e323f.firebasestorage.app',
    iosBundleId: 'com.example.potholeFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvM3i-F0vQKDhjWv8_B80kE2HMe8glhVs',
    appId: '1:325179381241:web:5247b279a71dfb5b659928',
    messagingSenderId: '325179381241',
    projectId: 'pothole-finder-e323f',
    authDomain: 'pothole-finder-e323f.firebaseapp.com',
    storageBucket: 'pothole-finder-e323f.firebasestorage.app',
    measurementId: 'G-WX1F9HYJSX',
  );
}
